import { NextResponse } from "next/server";
import OpenAI from "openai";
import { createServerSupabaseClient } from "@/lib/supabase";

// Initialize OpenAI client
const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
  try {
    const data = await req.json();
    const { 
      name, email, age, gender, height, bodyShape, 
      faceShape, skinTone, hairType, fashionPreferences, 
      lifestyle, stylingGoals 
    } = data;

    const systemPrompt = `You are an elite, highly sought-after personal luxury stylist and image consultant named Gayathri Sreekumar. Your tone is sophisticated, empowering, and highly articulate. You provide personalized, realistic, and curated styling advice based on the user's profile.

Respond in pure JSON format matching this schema exactly, without any markdown formatting or extra text:
{
  "clothingStyles": ["Style 1", "Style 2"],
  "colors": ["Color 1", "Color 2"],
  "hairstyle": "Detailed hairstyle suggestion",
  "grooming": "Detailed grooming or makeup/skincare recommendation",
  "accessories": ["Accessory 1", "Accessory 2"],
  "outfitGuidance": "General outfit construction and silhouette guidance",
  "confidenceTips": "Empowering style improvement and confidence tips",
  "occasionBased": {
    "work": "Professional/Workwear advice",
    "casual": "Casual everyday wear advice",
    "evening": "Evening or formal event advice"
  }
}`;

    const userPrompt = `Please analyze the following client profile and provide a luxury styling report.
Name: ${name || "Client"}
Age: ${age || "Not specified"}
Gender: ${gender || "Not specified"}
Height: ${height || "Not specified"}
Body Shape: ${bodyShape || "Not specified"}
Face Shape: ${faceShape || "Not specified"}
Skin Tone: ${skinTone || "Not specified"}
Hair Type: ${hairType || "Not specified"}
Fashion Preferences: ${fashionPreferences || "Not specified"}
Lifestyle/Profession: ${lifestyle || "Not specified"}
Styling Goals: ${stylingGoals || "Not specified"}`;

    console.log(`[Style Analysis] New request from ${email || "Anonymous"}`);

    if (!process.env.OPENAI_API_KEY) {
      console.error("[Style Analysis] OPENAI_API_KEY is missing");
      return NextResponse.json({ error: "OpenAI configuration missing" }, { status: 500 });
    }

    console.log("[Style Analysis] Generating report via OpenAI...");
    const completion = await openai.chat.completions.create({
      model: "gpt-4o-mini",
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt }
      ],
      response_format: { type: "json_object" },
    });

    const reportContent = completion.choices[0].message.content;
    if (!reportContent) throw new Error("No report generated by AI.");
    
    console.log("[Style Analysis] Report generated successfully.");
    const reportData = JSON.parse(reportContent);

    // Save to Supabase
    const supabase = createServerSupabaseClient();
    if (!supabase) {
      console.error("[Style Analysis] Supabase client failed to initialize (check env vars)");
      return NextResponse.json({ error: "Database configuration missing" }, { status: 500 });
    }

    console.log("[Style Analysis] Saving report to Supabase...");
    const { error: insertError } = await supabase.from("styling_reports").insert({
      user_name: name || "Anonymous",
      user_email: email || null,
      age: age || null, 
      gender: gender || null, 
      height: height || null, 
      body_shape: bodyShape || null, 
      face_shape: faceShape || null, 
      skin_tone: skinTone || null, 
      hair_type: hairType || null, 
      fashion_preferences: fashionPreferences || null, 
      lifestyle: lifestyle || null, 
      styling_goals: stylingGoals || null, 
      report_data: reportData,
      status: 'pending'
    });

    if (insertError) {
      console.error("[Style Analysis] Supabase Insert Error:", insertError);
      return NextResponse.json({ error: `Database error: ${insertError.message}` }, { status: 500 });
    }

    console.log("[Style Analysis] Report saved successfully.");

    return NextResponse.json({ success: true, message: "Report submitted for review" });
  } catch (error: any) {
    console.error("[Style Analysis] Uncaught Error:", error);
    return NextResponse.json({ error: error.message || "Failed to generate styling report" }, { status: 500 });
  }
}
